# Generated by Django 4.1.4 on 2022-12-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billtis', '0002_profile'),
    ]

    operations = [
    ]
