# Generated by Django 4.1.4 on 2022-12-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billtis', '0003_billtis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='place',
        ),
        migrations.RemoveField(
            model_name='table',
            name='place',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='menus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.menu'),
        ),
        migrations.AddField(
            model_name='place',
            name='tables',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.table'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='menu',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.product'),
        ),
    ]
