# Generated by Django 4.1.4 on 2022-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billtis', '0004_product_remove_profile_user_remove_menu_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='product',
        ),
        migrations.RemoveField(
            model_name='place',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tables',
        ),
        migrations.AddField(
            model_name='menu',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.place'),
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.menu'),
        ),
        migrations.AddField(
            model_name='table',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billtis.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
